.PHONY: clean All

All:
	@echo "----------Building project:[ Demo - Debug ]----------"
	@cd "C:\Users\Tamias65\Documents\GitHub\CMUMRSD\17630\Demo" && $(MAKE) -f  "Demo.mk"
clean:
	@echo "----------Cleaning project:[ Demo - Debug ]----------"
	@cd "C:\Users\Tamias65\Documents\GitHub\CMUMRSD\17630\Demo" && $(MAKE) -f  "Demo.mk" clean
